const { faker } = require('@faker-js/faker');

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [{
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'male',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/men/63.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'male',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/men/93.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'male',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/men/14.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'female',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/women/20.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'male',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/men/60.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'female',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/women/0.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'male',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/men/68.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'female',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/women/27.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'male',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/men/74.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'female',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/women/45.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'male',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'male',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/men/25.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'female',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/women/84.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: faker.person.firstName(),
      secondName: faker.person.lastName(),
      age: faker.number.int({ min: 25, max: 45 }),
      gender: 'male',
      email: faker.internet.email(),
      tel: faker.phone.number(),
      job: faker.person.jobDescriptor(),
      jobName: faker.person.jobTitle(),
      friends: faker.number.int({ min: 100, max: 400 }),
      avatar: 'https://randomuser.me/api/portraits/men/79.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
